### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by agentbarti** [Rozumek29/Instaling-Bot#4]
Witaj, moglbys zupdejtowac do najnowszej wersji Google Chrome? Ponieważ wywala driver teraz. Prosiłbym bardzo. Mogłbyś rownież dać discorda o ile takowego posiadasz.

**Comment by Rozumek29** [comment]
Pewnie, mój discord to Rozumek29#7360
A driver nie jest zaktualizowany bo instaling skończył się w mojej szkole i myślałem że nikt inny z tego nie korzysta. Napisz do mnie to powiem ci co i jak.
